version: '3'

volumes:
    etcd_gc_data:
        driver: local

services:
    etcd-gc:
      image: quay.io/coreos/etcd:v3.2.1
      volumes:
        - etcd_gc_data:/etcd-data
        - /usr/share/ca-certificates/:/etc/ssl/certs
      environment:
        - STATS_PORT=29340
      ports:
        - 2379:2379
        - 2380:2380
      networks:
        backend_devel_network:
          aliases:
            - etcd-gc.net.local
      command: "/usr/local/bin/etcd \
                --data-dir=/etcd-data --name etcd-gc \
                --initial-advertise-peer-urls http://127.0.0.1:2380 --listen-peer-urls http://0.0.0.0:2380 \
                --advertise-client-urls http://127.0.0.1:2379 \
                --listen-client-urls http://0.0.0.0:2379 \
                --initial-cluster etcd-gc=http://127.0.0.1:2380"

    cli-gc:
        build:
                context: .
                args:
                        version: 0.1.0-dirty
        environment:
            - STATS_PORT=29340
            - STATS_GWADDR=localhost
            - STATS_INTERVAL_TICKER=30s #https://golang.org/pkg/time/#ParseDuration
        restart: always
        ports:
            - "29340:29340"
            - "29341:29341"
        networks:
                backend_devel_network:
                        aliases:
                                - cli-gc.net.local

networks:
        backend_devel_network:
                external: true
