version: '3'

services:

        gconf.consul:
                image: consul:1.4.4
                hostname: getconf.consul
                container_name: getconf.consul
                restart: unless-stopped
                ports:
                - "8500:8500"
                - "8600:8600"
                - "8502:8502"
                command: "agent -dev -ui -client 0.0.0.0"
                networks:
                        backend_devel_network:
                                aliases:
                                - consul.acb.info

        gconf.etcd:
                image: quay.io/coreos/etcd:v3.3.12
                hostname: gconf.etd
                container_name: gconf.etcd
                volumes:
                        - etcd-data:/etcd-data
                        - /usr/share/ca-certificates/:/etc/ssl/certs
                restart: unless-stopped
                ports:
                        - "2379:2379"
                        - "2380:2380"
                        - "4001:4001"
                environment:
                        - HostIP
                networks:
                        backend_devel_network:
                                aliases:
                                - etcd.acb.info
                command: "/usr/local/bin/etcd \
                --name etcd0 \
                --data-dir '/etcd-data' \
                -advertise-client-urls http://${HostIP}:2379,http://${HostIP}:4001 \
                -listen-client-urls http://0.0.0.0:2379,http://0.0.0.0:4001 \
                -initial-advertise-peer-urls http://${HostIP}:2380 \
                -listen-peer-urls http://0.0.0.0:2380 \
                -initial-cluster-token etcd-cluster-1 \
                -initial-cluster etcd0=http://${HostIP}:2380 \
                -initial-cluster-state new"

networks:
        backend_devel_network:
                external: true

volumes:
        etcd-data:
                driver: local