version: '3'
volumes:
        etcd-data:
                driver: local
services:
        etcd:
                image: quay.io/coreos/etcd:v3.2.7
                hostname: etcd0
                container_name: etcd
                volumes:
                        - etcd-data:/etcd-data
                        - /usr/share/ca-certificates/:/etc/ssl/certs
                restart: always
                ports:
                        - "2379:2379"
                        - "2380:2380"
                        - "4001:4001"
                environment:
                        - HostIP
                networks:
                        backend_devel_network:
                                aliases:
                                        - etcd.acb.info
                command: "/usr/local/bin/etcd \
                --name etcd0 \
                --data-dir '/etcd-data' \
                -advertise-client-urls http://${HostIP}:2379,http://${HostIP}:4001 \
                -listen-client-urls http://0.0.0.0:2379,http://0.0.0.0:4001 \
                -initial-advertise-peer-urls http://${HostIP}:2380 \
                -listen-peer-urls http://0.0.0.0:2380 \
                -initial-cluster-token etcd-cluster-1 \
                -initial-cluster etcd0=http://${HostIP}:2380 \
                -initial-cluster-state new"
networks:
        backend_devel_network:
                external: true